// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: album.sql

package sqlc

import (
	"context"
)

const albumCreate = `-- name: AlbumCreate :one
INSERT INTO albums (spotify_id, name, track_amount, popularity)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type AlbumCreateParams struct {
	SpotifyID   string
	Name        string
	TrackAmount int32
	Popularity  int32
}

func (q *Queries) AlbumCreate(ctx context.Context, arg AlbumCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, albumCreate,
		arg.SpotifyID,
		arg.Name,
		arg.TrackAmount,
		arg.Popularity,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const albumGetBySpotify = `-- name: AlbumGetBySpotify :one
SELECT id, spotify_id, name, track_amount, popularity
FROM albums
WHERE spotify_id = $1
`

func (q *Queries) AlbumGetBySpotify(ctx context.Context, spotifyID string) (Album, error) {
	row := q.db.QueryRow(ctx, albumGetBySpotify, spotifyID)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.SpotifyID,
		&i.Name,
		&i.TrackAmount,
		&i.Popularity,
	)
	return i, err
}

const albumGetByUser = `-- name: AlbumGetByUser :many
SELECT a.id, a.spotify_id, a.name, a.track_amount, a.popularity
FROM albums a
LEFT JOIN album_users au on au.album_id = a.id
WHERE au.user_id = $1
`

func (q *Queries) AlbumGetByUser(ctx context.Context, userID int32) ([]Album, error) {
	rows, err := q.db.Query(ctx, albumGetByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Album
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.ID,
			&i.SpotifyID,
			&i.Name,
			&i.TrackAmount,
			&i.Popularity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const albumUpdate = `-- name: AlbumUpdate :exec
UPDATE albums
SET name = $2, track_amount = $3, popularity = $4
WHERE id = $1
`

type AlbumUpdateParams struct {
	ID          int32
	Name        string
	TrackAmount int32
	Popularity  int32
}

func (q *Queries) AlbumUpdate(ctx context.Context, arg AlbumUpdateParams) error {
	_, err := q.db.Exec(ctx, albumUpdate,
		arg.ID,
		arg.Name,
		arg.TrackAmount,
		arg.Popularity,
	)
	return err
}
