// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: track.sql

package sqlc

import (
	"context"
)

const trackCreate = `-- name: TrackCreate :one
INSERT INTO tracks (spotify_id, name, popularity)
VALUES ($1, $2, $3)
RETURNING id
`

type TrackCreateParams struct {
	SpotifyID  string
	Name       string
	Popularity int32
}

func (q *Queries) TrackCreate(ctx context.Context, arg TrackCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, trackCreate, arg.SpotifyID, arg.Name, arg.Popularity)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const trackGetByPlaylist = `-- name: TrackGetByPlaylist :many
SELECT t.id, t.spotify_id, t.name, t.popularity
FROM tracks t
LEFT JOIN playlist_tracks p_t ON p_t.track_id = t.id
WHERE p_t.playlist_id = $1
`

func (q *Queries) TrackGetByPlaylist(ctx context.Context, playlistID int32) ([]Track, error) {
	rows, err := q.db.Query(ctx, trackGetByPlaylist, playlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.SpotifyID,
			&i.Name,
			&i.Popularity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trackGetBySpotify = `-- name: TrackGetBySpotify :one
SELECT id, spotify_id, name, popularity
FROM tracks
WHERE spotify_id = $1
`

func (q *Queries) TrackGetBySpotify(ctx context.Context, spotifyID string) (Track, error) {
	row := q.db.QueryRow(ctx, trackGetBySpotify, spotifyID)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.SpotifyID,
		&i.Name,
		&i.Popularity,
	)
	return i, err
}

const trackUpdateBySpotify = `-- name: TrackUpdateBySpotify :exec
UPDATE tracks
SET name = $2, popularity = $3
WHERE spotify_id = $1
`

type TrackUpdateBySpotifyParams struct {
	SpotifyID  string
	Name       string
	Popularity int32
}

func (q *Queries) TrackUpdateBySpotify(ctx context.Context, arg TrackUpdateBySpotifyParams) error {
	_, err := q.db.Exec(ctx, trackUpdateBySpotify, arg.SpotifyID, arg.Name, arg.Popularity)
	return err
}
