// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_album.sql

package sqlc

import (
	"context"
)

const userAlbumCreate = `-- name: UserAlbumCreate :one
INSERT INTO user_albums (user_id, album_id)
VALUES ($1, $2)
RETURNING id
`

type UserAlbumCreateParams struct {
	UserID  int32
	AlbumID int32
}

func (q *Queries) UserAlbumCreate(ctx context.Context, arg UserAlbumCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, userAlbumCreate, arg.UserID, arg.AlbumID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const userAlbumDelete = `-- name: UserAlbumDelete :exec
DELETE FROM user_albums
WHERE id = $1
`

func (q *Queries) UserAlbumDelete(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, userAlbumDelete, id)
	return err
}
