// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_show.sql

package sqlc

import (
	"context"
)

const userShowCreate = `-- name: UserShowCreate :one
INSERT INTO user_shows (user_id, show_id)
VALUES ($1, $2)
RETURNING id
`

type UserShowCreateParams struct {
	UserID int32
	ShowID int32
}

func (q *Queries) UserShowCreate(ctx context.Context, arg UserShowCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, userShowCreate, arg.UserID, arg.ShowID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const userShowDelete = `-- name: UserShowDelete :exec
DELETE FROM user_shows
WHERE id = $1
`

func (q *Queries) UserShowDelete(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, userShowDelete, id)
	return err
}
