// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_playlist.sql

package sqlc

import (
	"context"
)

const userPlaylistCreate = `-- name: UserPlaylistCreate :one
INSERT INTO user_playlists (user_id, playlist_id)
VALUES ($1, $2)
RETURNING id
`

type UserPlaylistCreateParams struct {
	UserID     int32
	PlaylistID int32
}

func (q *Queries) UserPlaylistCreate(ctx context.Context, arg UserPlaylistCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, userPlaylistCreate, arg.UserID, arg.PlaylistID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const userPlaylistDelete = `-- name: UserPlaylistDelete :exec
DELETE FROM user_playlists
WHERE id = $1
`

func (q *Queries) UserPlaylistDelete(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, userPlaylistDelete, id)
	return err
}
