// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"
)

const userCreate = `-- name: UserCreate :one
INSERT INTO users (name, email, uid)
VALUES ($1, $2, $3)
RETURNING id
`

type UserCreateParams struct {
	Name  string
	Email string
	Uid   string
}

func (q *Queries) UserCreate(ctx context.Context, arg UserCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, userCreate, arg.Name, arg.Email, arg.Uid)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const userGet = `-- name: UserGet :one
SELECT id, name, email, uid
FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) UserGet(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, userGet, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Uid,
	)
	return i, err
}

const userGetByUID = `-- name: UserGetByUID :one
SELECT id, name, email, uid
FROM users
WHERE uid = $1 LIMIT 1
`

func (q *Queries) UserGetByUID(ctx context.Context, uid string) (User, error) {
	row := q.db.QueryRow(ctx, userGetByUID, uid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Uid,
	)
	return i, err
}
